project_id = "ldhgwqeuvbvlmvyywmaf"

[functions.log-login-event]
verify_jwt = false

[functions.generate-face-vector]
verify_jwt = true

[functions.search-face-vector]
verify_jwt = true

[functions.batch-generate-face-vectors]
verify_jwt = true

[functions.verify-face-login]
verify_jwt = false

[functions.save-face-data]
verify_jwt = false

[functions.verify-biometric-login]
verify_jwt = false

[functions.check-device-access]
verify_jwt = false

[functions.manage-user-device]
verify_jwt = true