project_id = "ldhgwqeuvbvlmvyywmaf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge_functions]
enabled = true
port = 54327

[functions.get-mapbox-token]
verify_jwt = false

[functions.realtime-chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.text-to-voice]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.batch-generate-embeddings]
verify_jwt = true

[functions.face-recognition]
verify_jwt = true

[functions.generate-face-embedding]
verify_jwt = true

[functions.face-verification]
verify_jwt = true

[functions.fetch-facebook-posts]
verify_jwt = false