// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldhgwqeuvbvlmvyywmaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkaGd3cWV1dmJ2bG12eXl3bWFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzUxNjcsImV4cCI6MjA2OTgxMTE2N30.wsi9hbvktGcQSQ7FR6-IyZcXW3ZWRIW4S-EiKp_VW1I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});