// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaxwdfyasunyhlhrrrwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9heHdkZnlhc3VueWhsaHJycnd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MzczMDYsImV4cCI6MjA2OTQxMzMwNn0.RL_v1HarcH-sDNBd8JTMcUmWpX6bcPF1z7EUouLjlm0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});